 - name: Setup Machine Cluster
   hosts: cluster
   become: true
   gather_facts: no
   tasks: 
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install
      apt:
        name: docker.io
        state: present

    - name: Install Helm
      shell:
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 &&
        chmod 700 get_helm.sh &&
        ./get_helm.sh
    

    - name: Install Kubectl
      shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
 
 - name: Setup Machine Rancher
   hosts: rancher
   become: true
   gather_facts: no
   tasks: 
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Install Rancher
      shell: docker run -d --name rancher --restart=unless-stopped -v /otp/rancher:/var/lib/rancher -p 80:80 -p 433:443 rancher/rancher:v2.7-head